---
title: "MuSICA Output Comparison Summary"
output: 
    html_document:
      css: toc.css
      toc: yes
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE)
```



```{r, results = 'asis'}
if (!missing(template)) {
  cat("\n\n#",template,"\n")
}
```


```{r, results = 'asis'}
res <- lapply(list_var, function(this_var) {
  knitr::knit_child(
    'template_cmp_child.Rmd', envir = environment(), quiet = TRUE
  )
})
cat(unlist(res), sep = '\n')
```


```{r, results = 'asis'}
if (add_study_site) {
    cat("\n\n# Study Site\n")
  
dflat <- sapply(x, function(dx) (get_variable(dx, "latitude"))$latitude)
dflon <- sapply(x, function(dx) (get_variable(dx, "longitude"))$longitude)
m <- leaflet::leaflet() %>%
  leaflet::addTiles() %>%  # Add default OpenStreetMap map tiles
  leaflet::addMarkers(lng = dflon, 
                      lat = dflat, 
                      popup = names(x),
                      clusterOptions = leaflet::markerClusterOptions())
m  # Print the map
}
```

