---
title: "News"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{News}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

## <i class="fas fa-code"></i> Development updates
### 0.1.17
  * added option to plot Water Table Depth on soil heatmaps  
  * added several tool function: get_version, get_species_list, 
  list_allvar, get_timeline_df

### 0.1.16
  * Default graphical device set to ragg for the shiny app to allow plotting 
  heatmap with geom_raster and more than 2^15-1 data on the x scale on some system.
  * Heatmap reverted to use geom_raster again. May need to export plot with ragg::agg_png

### 0.1.15 
  * Heatmap now use geom_tile instead of geom_raster as the latter appeared 
  to have limits on the number of data possible to use in the x axis 
  (bug from 25/04/2024)
  
### 0.1.14
  * Removed unnecessary check in conversion for mmol/m2/s to kg/m2/s

### 0.1.13
  * Add unit conversion kg/m2/s to kg/m2/dt
  * Add get_timeline and plot_timeline 
  
### 0.1.12
  * updated summary_markdown to incorporate observations
  * summary_markdown can now have title as argument
  * fixed date to read output < Jan. 2019

### 0.1.11
  * Adjusted graphic height for dygraphs
  * increased number of decimals in dygraph

### 0.1.10 (2024/02/20)
  * Increased number of dygraphs panel from 3 to 5.

### 0.1.9
  * added unit conversion for q_h2o_soil, q_h2o_soil_vap, q_h2o_soil_cracks in v2 output
  
### 0.1.8
  * added unit conversion for q_h2o_soil_liq in v2 output
  
### 0.1.7
  * heatmap can now use real height/depth value instead of the number of layer.
  * `grDevices` is now the default graphic devices in the shiny app for better 
  rendering of `geom_tile` plots.
  * fixed bug with time-independent variable in MuSICA v2 output.

### 0.1.6
  * properly format variable with empty units

### 0.1.5
  * added conversion mm/dt to or from kg/m2/s
  * added conversion mmol/m2/s to from kg/m2/s
  * added automatic conversion for transpiration in MuSICA v2 output files
  * added get_variable_raw to avoid code repetition in get_variable

### 0.1.4
  * shiny app now use a separate css file
  * improved readability of the app. Graphics, regenerate and export button have
  now a fixed position. Left sidebar has now a scroll bar.
  
### 0.1.3
  * get_variable_comparison return models as a factor, allowing facet to be plot 
  in the correct order.
  
### 0.1.2
  * in the shiny app, for heatmap and daily heatmap, facet default to models if possible
  * fixed bugs with model differences and heatmap/daily_heatmap
  * small fixes for compliance to new package convention (import and package doc)

### 0.1.1
  * increased left panel width for shinymusica tab1


### 0.1.0 Alpha version
  * First documentation and examples
  * compliance to R CMD check
  * Added possibility to move time window
  * convert root uptake units for dev_jerome output

### 0.0.9
  * Added options to deactivate each dygraph
  * Added option to adjust number of facet rows
  * Added option to add year to the timeframe

### 0.0.8
  * Revamped shiny app to be more flexible with the static graphics tab

### 0.0.7
  * Revamped ggplot_variable
  * added get_two_variables
  * revamped Shiny app to mobilize more shinyjs functionnalities

### 0.0.6
  * Improved Shiny App and added several types of graphics

### 0.0.5
  * Added a second tab to the shiny app
  
### 0.0.4
  * Added Shiny App
  
### 0.0.3
  * added comparison function
  
### 0.0.2 
  * bugfix
  
### 0.0.1 
  * alpha version