# shinymusica ---------------------------------------------------------
##' @name shinymusica
##' @author Remi Lemaire-Patin
##' 
##' @title ShinyApp to explore MuSICA model output
##' 
##' @description shinymusica runs a Shiny application to explore multiple MuSICA
##' model output
##' 
##' 
##' @param x a named list of \code{ncdf4} object. Outputs generated by several
##'  MuSICA model run.
##' 
##' @return
##' 
##' A \code{shiny} application
##' 
##' @family shiny
##'   
##' @examples
##' library(ncdf4)
##' x <- nc_open(system.file("extdata", "musica_out_2006_demo.nc", package = "musica.tools"))
##' x.list <- list("model1" = x, "model2" = x)
##' # Not Run
##' # shinymusica(x.list)
##' 
##' @importFrom shiny shinyApp
##' @export
##' 
##' 


shinymusica <- function(x) {
  # shinyOptions("shiny.useragg" = FALSE,
  #              "shiny.usecairo" = FALSE)
  options("shiny.useragg" = FALSE)
  options("shiny.usecairo" = FALSE)
  shinyApp(musica_ui(x), musica_server(x))
}